### ISSUE TITLE
feed dependency

### ISSUE THREAD

**Issue by dzhus** [Minoru/hakyll-convert#15]
Hi,

It looks like the latest version of `hakyll-convert` currently published on Hackage has a dependency on [`feed`][feed] package without an upper bound specified.

A new version of `feed` will be released soon, incorporating [non-backwards compatible changes][feed-pr] to `feed` interface (`String` was replaced with `Text` throughout and `xml-types` types were adopted). Changes are largely mechanical but you'll probably want to ensure that future version of `hakyll-convert` can build with newer `feed`.

To prevent breakage, you may want to release a new version of `hakyll-convert` with an upper bound specified now, then push a version compatible with `feed-1.0` after that comes out later.

Use the tip of the `feed` PR to test your package against: https://github.com/dzhus/feed/commit/259bab0. Please report any issues to the aforementioned [PR thread][feed-pr].

[feed]: http://hackage.haskell.org/package/feed
[feed-pr]: https://github.com/bergmark/feed/pull/20

**Comment by Minoru** [comment]
Thanks for the heads-up! I'll look into this on the weekend.

**Comment by dzhus** [comment]
feed-1.0 has been released a while ago

**Comment by Minoru** [comment]
Yeah, sorry, I dropped the ball. And if I'm being realistic, I don't think I'll get to this issue anytime soon.
