### ISSUE TITLE
support comments

### ISSUE THREAD

**Issue by kowey** [Minoru/hakyll-convert#3]
Most of the work is there.  We should have a `DistilledComment` type perhaps.  The default converter could have an option to include comments or not.

**Comment by Minoru** [comment]
To close this issue, the following has to be done:

- [ ] figure out how Wordpress exports comments. For Blogger, they're part of the usual dump. Is that so for Wordpress?
- [ ] make `Hakyll.Convert.Wordpress.distill` accept a `Bool` indicating if comments are to be exported. If it's `True`, comments should be put into the post's body, right at the end of it (see [`Blogger.hs:178-184`](https://github.com/Minoru/hakyll-convert/blob/master/Hakyll/Convert/Blogger.hs#L178-L184) for what I mean);
- [ ] update help message (it currently says that we only export Blogger comments);
- [ ] without doubt, some common parts will present themselves. These should be factored out into `Hakyll.Convert.Common`. (And while we're at it, maybe turn that `Bool` into something more descriptive.)

**Comment by Minoru** [comment]
The last item of the plan (the refactoring) was split out into #13.
